version: '3'

services:
    # Etherpad: real-time collaborative document editing
    etherpad:
        image: jitsi/etherpad:latest
        restart: ${RESTART_POLICY}
        environment:
            - ETHERPAD_DISABLE_IP_LOGGING
            - ETHERPAD_LOG_LEVEL
        networks:
            meet.jitsi:
                aliases:
                    - etherpad.meet.jitsi
